### ISSUE TITLE
Handle 1D PDFs with negative values

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#120]
With the use of ASTs reporting fluxes (and not just magnitudes), the 1D PDF code defaults to a 1D pdf filled with zeros (in the workflow branch - solution instead of erroring out).  The issue is with 1D PDFs that need to be created with a log spacing for computational reasons.  This only happens for the case of the model predicted fluxes when they become negative due to the AST bias term (which is reality).

This was discussed in ISM group meeting and various possible solutions suggested including:
luptitudes (luptun & gunn 1999)
or
symlog numpy
or
asinh 

Additional info: http://www.sdss3.org/dr10/algorithms/magnitudes.php

**Comment by lea-hagen** [comment]
After briefly looking into this, here are a few notes:
* The idea for this issue is to make the PDFs for fluxes, and fluxes can be negative, so a simple log isn't optimal.
* It is unclear where in the code the log is being taken.  It may be in beast/fitting/fit.py (lines ~300-375), or perhaps in beast/fitting/pdf1d.py (lines 38-41).
* next thing to do: figure out where the log happens, and make sure the new scaling only affects fluxes, and not masses (which are also log scaled).
