### ISSUE TITLE
isochrone download changed

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#265]
The downloaded isochrone tested in the regression test suite has changed.  Seems like minor changes, but maybe someone else knows why.  @lcjohnso ?   @mfouesneau  ?

https://travis-ci.org/BEAST-Fitting/beast/jobs/447896795

**Comment by mfouesneau** [comment]
All recent commits are not remotely near the isochrone codes. Changes must be on the server side. Possibly the reported float precision in the files?

**Comment by karllark** [comment]
Yes, I agree.  I assumed it was on the server side.  Wondered if you or Cliff knew of any changes that would affect the delivered isochrones.

**Comment by lcjohnso** [comment]
According to the Padova Download website, they just updated to 3.1 from 3.0 on 29 Oct 2018:
"CMD v3.1: It is now possible to choose the dust composition separately for C and M stars. Bug corrected in current mass for massive stars + mass loss always negative."

Perhaps the bug fix regarding current mass explains the difference?  I'll check to see.

**Comment by lcjohnso** [comment]
Yes -- there are two differences between the files / isochrone models:
1) For stars with M >~ 12 Msun (here, for logA <= 7.0), M_actual was miscalculated and was reported as ~1.0 -- far lower than its correct value.
![isodif_mact](https://user-images.githubusercontent.com/2006101/47754218-2af1cf80-dc68-11e8-9aee-a52735aad5ba.png)

2) This same subsample of stars also had incorrect log(g) values -- they were about ~1.3 too small (1.0 rather than 2.3).
![isodif_logg](https://user-images.githubusercontent.com/2006101/47754217-2af1cf80-dc68-11e8-8873-f6c1262bf4c9.png)

The newly corrected values that result from the bug fix seem more accurate, so seems that the comparison file should be updated.  The large implications of inaccurate M_act and log(g) are unknown to me at this time, but should be considered for BEAST runs that used PARSEC models.

**Comment by karllark** [comment]
Interesting.  Thanks for detailing the changes.  definitely the new isochrones should be used.   I'll do a sample fit to see what changed.  But we will need to investigate further.  

@lea-hagen : maybe you could do a test using one of the METAL fields?  Would be good to test if this makes a significant different for real data.  Basically, if you recreate the BEAST grid, it will automatically have this fix as it happened upstream on the PADOVA website.

**Comment by karllark** [comment]
Updated the regression tests.  Still be good to check on a larger run - but just to know the impact.  The new isochrones are better (bugfixes always good!).

**Comment by karllark** [comment]
Closing this issue as it has been dealt with, understanding the impact would be good, but not needed.
