### ISSUE TITLE
sizes of source density bins

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#398]
For production runs, we're creating different noise models for each source density bin.  How do we determine these bins?  Here's my quick brainstorm about the two options:

| Method | Advantages | Disadvantages |
| ---- | ---- | ---- |
| **1. Constant spacing**: create noise models for 0-1 sources/arcsec2, 1-2 sources/arcsec2, etc.  The BEAST paper used integer spacing. | Noise models directly comparable between fields.  Already works nicely with file structure/labeling. | Need to decide if integer spacing is the best option. |
| **2. Fractional spacing**: divide the range of measured source densities into N bins. | Can more finely space the noise models when the source density range is small. | Catalogs with a larger range of source densities will have coarser sampling of noise model. |

I prefer the constant spacing, but I'm very much open to discussion.

@karllark, @drvdputt

**Comment by lea-hagen** [comment]
And a similar question: if the background levels have large spatial variability (e.g., from gas emission), are there any insights into how to bin those?

**Comment by drvdputt** [comment]
I have some insight regarding the background emission.

For IC63, I made 4 different noise models, one per region of similar background emission intensity. (By splitting up the AST results into 4 files, using the AST positions to find which region=background level they belong to.) The background bins to determine the regions were log-spaced over the total intensity range. 

The result is the following plot: [toothpick_multi.pdf](https://github.com/BEAST-Fitting/beast/files/3680278/toothpick_multi.pdf)

As you can see, only bin 4 is different from the rest. There's two important remarks to make here.
1. Bin 4 is probably the only one in which the intensity is high enough to matter.
2. The area over which the intensity is this high is rather small. So bins 1-3 are averaged over rather large areas, while bin 4 is more a particular area. This could also explain the difference.

Bins 1-3 should probably be only one bin, while bin 4 could be split up more to see a more gradual change between the noise models. However, this will make the relevant area even smaller in this specific case.
So, taking a linear spacing instead of a log spacing would be the better choice, but it should be kept in mind that this will cause the ASTs for the noise model to be concentrated in rather small areas (which might be desirable behaviour nonetheless).

Concluding (in the context of IC63):
- A linear spacing would generate separate noise models for a number of compact high-intensity areas. The other, low-intensity areas will be covered by one or two noise models instead.

- A log spacing does the opposite: the high-intensity areas are all covered by a single noise model, while the low-intensity areas (between which the differences might be irrelevant) have multiple noise models assigned to them.

**Comment by lea-hagen** [comment]
Thanks, that's really helpful!  I have a couple follow-up questions about the background bins.  How did you choose to do 4 bins, rather than more or fewer?  What were the cutoffs between bins (presumably in HST units of electrons/sec)?

**Comment by drvdputt** [comment]
First, a correction: apparently I was already using linear spacing. 

I printed out the bin edges and got  
`[-0.02354479  0.0002293   0.02400339  0.04777747  0.07155156]`

This is in the units of the HST image, divided by surface area in pixel coordinates, so e s-1 "per square pixel".

Note that this whole approach was more of an experiment in my case though. I did not actually use these noise models for the paper, as I found the results for the sources in bin 4 to be not much different. 

Doing 4 bins was mainly motivated by limitations on hard drive space. Originally, I wanted to do 8.
I didn't come to that number (8) in some more formal way; I just looked at plots like this ([regions.pdf](https://github.com/BEAST-Fitting/beast/files/3682358/regions.pdf)), and saw if the generated regions were more or less contiguous.

But based on my previous comment, I think some sort of manual choice of bin edges might be better: put everything where the background is too low to matter in one bin, and then discretize the range of intensities above that.
The ideal choice probably depends on the resolution and/or quality of the background map (which in turn depends on the region being modeled).

**Comment by karllark** [comment]
Is this issue ok for closing?  Or is more discussion needed?

**Comment by karllark** [comment]
Ping

**Comment by lea-hagen** [comment]
I don't think a decision has been reached (as in, the spacing shall be `N`).  Though we should make some plots to show that the noise model isn't changing too rapidly between bins.  I'll add a note about that to #333.  @karllark, I'll leave it up to you whether that means this issue can be closed!

**Comment by karllark** [comment]
Closing after linking to #333.
