### ISSUE TITLE
error when downloading library files

### ISSUE THREAD

**Issue by astronomeralex** [BEAST-Fitting/beast#403]
when following the directions to download the library files, i get this error:
```
python -m beast.tools.get_libfiles
Downloading http://www.stsci.edu/~kgordon/beast/vega.hd5
|======================================================================================| 174k/174k (100.00%)         0s
Traceback (most recent call last):
  File "/Users/alex/code/anaconda/envs/astroconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/alex/code/anaconda/envs/astroconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alex/code/beast/beast/tools/get_libfiles.py", line 20, in <module>
    nfilename = _download_rename(clib, libs_server, __ROOT__)
  File "/Users/alex/code/beast/beast/tools/get_libfiles.py", line 14, in _download_rename
    copyfile(fname_dld, local_loc + filename)
  File "/Users/alex/code/anaconda/envs/astroconda/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alex/code/beast/beast/libs/vega.hd5'
```
I'm using the development version of the code installed from github. 

![image](https://user-images.githubusercontent.com/3718991/66709153-9030ba80-ed2b-11e9-8d63-b9ee0d9b24e3.png)

**Comment by karllark** [comment]
Thanks for raising this issue!

The issue is that none of the possible locations for installing the files exist.  Check out [the library location options](https://beast.readthedocs.io/en/latest/install.html#beast-library-files).  Your best bet may be to create a `.beast` directory under your home directory.  Then the files should be installed there.  

This issue has pointed out to me that we should probably remove the 3rd option (quite "hacky") and have the script create the `.beast` subdirectory if it doesn't exist (and the BEAST_LIBS environment variable is not set).

**Comment by astronomeralex** [comment]
Agreed. While the documentation does clearly state that I should have made the directory, it's probably easier to just make the .beast directory automatically. I'm happy to make that bug fix.

**Comment by karllark** [comment]
That would be awesome!
