### ISSUE TITLE
DOC: cleanup TOC and install instructions

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#492]
The doc main page is getting a bit confusing.  For example, we have multiple install instructions for different purposes (user, developer, production) and it is not clear how to pick between them.

**Comment by mdecleir** [comment]
I agree that the main page is confusing. The installation instructions are a separate section, but if you want to install as a developer, you have to look at Developer Documentation -- How to contribute. That page includes install instructions, but also how to contribute. And on top, the main page has another section called "Contributing"... I will try to clean up a bit.

**Comment by karllark** [comment]
Great!

**Comment by mdecleir** [comment]
I looked at the main page, but I think we should agree first on the structure of this page. Do we want a separate section for the installation, and split that up for users/developers. Or do we want everything in 1 document? Or should we add the installation for developers to the developers section... etc...

**Comment by karllark** [comment]
I'm not sure.  Could you propose an organization - maybe in outline form in a comment here?  Then we could discuss.

**Comment by mdecleir** [comment]
I posted a suggestion for the lay-out of the main page on the Slack #hackday channel, because I cannot add a document here. My suggestion is to get rid of the "Developer documentation" section, and add the information that was there (the basic workflow on how to contribute) to the "Contributing" section. My feeling is that "Developer documentation" is too scary for new people, while "contributing" sounds more accessible. But then, in the current documentation, there is no basic workflow on how to contribute in that section, only links to read the Astropy pages, which feels like too much effort. So I think moving the "how to contribute" workflow from the old "Developer documentation" to the "Contributing" section would solve that. Does that make sense?

**Comment by mdecleir** [comment]
And, we could also add a section on that page with Publications that use the BEAST as suggested in issue #473.

**Comment by karllark** [comment]
The reorg looks good. 

I'm not sure the "New User Interface" is all that useful.  It is very short.  Maybe this could be re-titled and expanded to something like quickstart?

**Comment by mdecleir** [comment]
> The reorg looks good.
> 
> I'm not sure the "New User Interface" is all that useful. It is very short. Maybe this could be re-titled and expanded to something like quickstart?

I actually don't really understand the "new user interface". Isn't that the standard way to run the beast?

**Comment by mdecleir** [comment]
Concerning the conflicts: Is the required python 3.6 or 3.7?

**Comment by mdecleir** [comment]
> > The reorg looks good.
> > I'm not sure the "New User Interface" is all that useful. It is very short. Maybe this could be re-titled and expanded to something like quickstart?
> 
> I actually don't really understand the "new user interface". Isn't that the standard way to run the beast?

It turns out this page could be removed, because it was not very useful.

**Comment by mdecleir** [comment]
This issue has been assessed in PR #670.
